name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - "code/backend/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Image Name to lowercase
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./code/backend
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Image Name to lowercase
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create .env file
        run: |
          cat <<EOF > .env
          ${{ secrets.ENV_FILE }}
          NODE_ENV=production
          PORT=3000
          EOF

      - name: Pull new Docker image
        run: docker compose pull

      - name: Restart containers
        run: docker compose up -d

      - name: Clean unused images
        run: docker image prune -af
